[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --prefix apps/server --legacy-peer-deps"]

[phases.build]
cmds = [
  "cd apps/server && npx prisma generate && npx tsc"
]

[start]
cmd = "node apps/server/dist/index.js"
